### PR TITLE
removed skill_level assoc from job_skills

### PR DESCRIPTION
**Pull request by patmbolger**

### CODE REVIEW

**Comment by joaopapereira** [comment]
Why are we removing this association?

**Comment by patmbolger** [comment]
The association was actually removed on the prior PR 15 days ago.  In this PR I just removed a foreign key that was inadvertently left in the job_skills table.

Salem had proposed dropping the SkillLevel as well as the Skill model from the design.  We discussed this and decided to drop SkillLevel but retain Skill (decisions are noted in bold here: http://www.agileventures.org/projects/metplus/documents/job)

In particular:

"skill_level - this might be OK to drop, since skill_level required for a specific skill and for a specific job could be implicit to min_years and also covered in the job description - **drop this model**"

We thought that generic skill-level descriptions - not specific to any skill or any category of job - would not be very useful and cluttered up the design.  For example:

    name: Beginner
    description: Has basic skills and can work with minimal supervision on relatively simple tasks

does not say much that could be much better explained in the job description, and also may not be appropriate for all "Beginner" level skills for all skills and all jobs.

We can certainly reopen this if you think SkillLevel would provide value.

**Comment by joaopapereira** [comment]
Not sure if this is a good thing, maybe we need to talk a little bit about this

**Comment by joaopapereira** [comment]
After our talk I believe I can merge this PR

**Pull request merged**
